
<?php
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\AlertCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\taxonomy\Entity\Term;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\alter_url\Controller\urlController;
use Drupal\Component\Utility\Html;


/**
 * Implements hook_pathauto_alias_alter().
 */



function alter_url_pathauto_alias_alter(&$alias, array &$context) {
  if ($new_alias = (new urlController())->generate($context)) {
        $alias = $new_alias;
      }
}

function generate($context)
{
    if ($context['bundle'] === 'article' && ($context['op'] == 'insert' || $context['op'] == 'update')) {
        return $this->assembleAlias($context['data']['node']);
    }
}

function assembleAlias($entity)
{
    if ($entity->getEntityTypeId() === 'node') {
        if ($entity->bundle() === 'article') {
            if ($texo = $entity->get('field_course_name')->getValue()) {
                foreach ($texo as $data) {
                    $term = Term::load($data['target_id']);
                    $name = $term->getName();
                    $taxonomy_name = $term->bundle();
                }
            }           
            $url = '/' . $taxonomy_name . '/' . $name;
            echo $url ;die;
            return $url;

        }
    }
}


