<?php

/**
 * @file
 * Provides a profile[d[d[d[d[d[d[dmy_profile entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\content_entity_type\Entity\MyProfile;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function content_entity_type_theme() {
  return [
    'My_Profile' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for profile[d[d[d[d[d[d[dmy_profile templates.
 *
 * Default template: My-Profile.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the profile[d[d[d[d[d[d[dmy_profile information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_My_Profile1(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function content_entity_type_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish profile[d[d[d[d[d[d[dmy_profiles.
      $storage = \Drupal::entityTypeManager()->getStorage('My_Profile');
      $My_Profile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($My_Profile_ids) as $My_Profile) {
        $My_Profile->set('status', FALSE);
        $My_Profile->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize profile[d[d[d[d[d[d[dmy_profiles.
      $storage = \Drupal::entityTypeManager()->getStorage('My_Profile');
      $My_Profile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($My_Profile_ids) as $My_Profile) {
        $My_Profile->setOwnerId(0);
        $My_Profile->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function content_entity_type_user_predelete(UserInterface $account) {
  // Delete profile[d[d[d[d[d[d[dmy_profiles.
  $storage = \Drupal::entityTypeManager()->getStorage('My_Profile');
  $My_Profile_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $My_Profiles = $storage->loadMultiple($My_Profile_ids);
  $storage->delete($My_Profiles);
}
